### ISSUE TITLE
Whether testing resource must be installed or not is unclear

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#231]
Discussed in https://github.com/ros-industrial-consortium/descartes/pull/202#pullrequestreview-76897337

One solution is as done in the referenced PR, create a shared package. This is clean but sounds costly.
It would be great if we have a way that doesn't require special changes to the packages.

I can thinkf of [PKGS_DOWNSTREAM](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst). Testing resources in the packages listed here can be non-installed IIRC.

```
PKGS_DOWNSTREAM (default: explained): Packages in downstream to be tested. By default, TARGET_PKGS is used if set, if not then BUILD_PKGS is used.
:
TARGET_PKGS (default: not set): Used to fill PKGS_DOWNSTREAM if it is not set. If not set packages are set using the output of catkin_topological_order for the source space.
```

**Comment by ipa-mdl** [comment]
In general tests should not get installed (IMHO).
If you want to share test files to dependent packages, then installing them is a must.
And in this case it would be good to move them into dedicated packages to have a minimum set of dependencies for run-time-only users of the regular packages.
With  `catkin-tools` this gets even more complicated, because only installed file can be used in the same catkin workspace. (In contrast `catkin_make install` still uses the shared devel space.)
