### ISSUE TITLE
ABI check feature not functional on ROS Indigo?

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#258]
Reported in https://github.com/ros-drivers/openni2_camera/pull/75#issuecomment-351324425

**Comment by ipa-mdl** [comment]
It works with actionlib https://travis-ci.org/ros-industrial/industrial_ci/jobs/328743544

**Comment by ipa-mdl** [comment]
I think the issue here that nodelet libraries (or plugins in general) do not have an API/ABI and therefore abi-complicance-checker fails.
On lunar some symbols from OpenNI get exported, so this is just coincident..

We have some options:
1. implement blacklist, e.g. `ABI_CHECK_BLACKLIST='openni2_camera_nodelet'`
2. skip libraries with this error code
3. skip all plugins

The first option is very specific, less error-prone, not user-friendly (user can and must speficy it).
The second option might blacklist libraries that don't contain any symbols by accident.
The third option ist hard to implement and might skip hybrid libraries that should get checked.
