### ISSUE TITLE
Make master branch the default

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#494]
I would propose to make the switch until end of June.
This should be announced in #493 as well.

Schedule:

April 8: 
1. update migration guide
1. merge #397 
2. tag version 0.9.0 for legacy
2. tag version 0.10.0 for master
3. branch off `legacy_transitional` from `legacy` 
4. add warning output about deprecation to `legacy_transitional`
5. make `legacy_transitional` the default branch
6. ROS discourse announcment

May 25:
1. ~~change warning in `legacy_transitional` to announce upcoming transition~~

June 8:
1. branch off `master_transitional` from `master` 
2. add warning output about transition to `master_transitional`
3. make `master_transitional` the default branch
4. remove  `legacy_transitional` 

June 29:
1. make `master` the default branch
2. remove  `master_transitional`
3. close this issue :tada: 

@130s, @miguelprada, @gavanderhoorn: Any objections?

**Comment by gavanderhoorn** [comment]
June seems pretty far away.

We've had a grace period of many months (a year perhaps?) already.

End of May would seem sufficient to me, but I'm not in a hurry, and if you prefer end of June that would also be fine.

I would recommend to be vocal about it. So Discourse, the tracker here (perhaps this issue is already sufficient), and, maybe, also have `legacy` branch print a notice in the logs. Yes, "no one" reads those as long as everything is green, but it might still pay off if/when someone happens to *do* read the log for whatever reason.

**Comment by ipa-mdl** [comment]
> June seems pretty far away.

I am okay with "in June / after May" as well..
(-> 2 months of grace period after the announcement)

> maybe, also have legacy branch print a notice in the logs

Yes, this should get added to #397

**Comment by ipa-mdl** [comment]
> Yes, this should get added to #397

I have just decided against this..
Instead, I will create a "transitional" branch, which will show a warning.
This branch can be deleted safeky after master is default again.

**Comment by ipa-mdl** [comment]
I have updated the schedule.
The switch will happen on June 8. One year after the [announcement](https://discourse.ros.org/t/industrial-ci-migration-needed-for-recent-and-future-changes/9462)

**Comment by ipa-mdl** [comment]
switched to `master_transitional`

**Comment by ipa-mdl** [comment]
switched to `master` :tada:

**Comment by gavanderhoorn** [comment]
Now to see how many CI setups get broken ;)
