### ISSUE TITLE
Why $BUILDER var?

### ISSUE THREAD

**Issue by davetcoleman** [ros-industrial/industrial_ci#72]
Reviewing the ``travis.sh`` its not clear to me why a BUILDER variable exists? Do you really plan on supporting catkin_make in the future? Seems to add extra complexity to an already complicated travis script

**Comment by 130s** [comment]
Sorry for the delayed response.
Yes, `BUILDER` is reserved for other build tool. There's already an incomplete PR https://github.com/ros-industrial/industrial_ci/pull/23 for `catkin_make_isolate` and as the discussed in https://github.com/ros-industrial/industrial_ci/issues/21 we might want to add `ament` support if there's need.

In a PR #67 that I'll soon finalize and merge, I've started refactoring since as you said current script is getting complicated (I know the HEAD is already diverged from #67 but I'll manually cherry-pick the latest change).
